#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     snsr_accel1,    sensorI2CCustom)
#pragma config(Sensor, S3,     snsr_accel2,    sensorI2CCustom)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     driveLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     driveRight,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drivers/hitechnic-accelerometer.h"
//#include <HTAC-driver.h>
#include "datlog.h"

#define LOG_VAL accel_x
#define COUNTDOWN 5
#define MAX_FILESIZE 100
#define ARRAY_LEN 1800

string FILENAME = "test";
int theta = 0;
int gravity = 195;
int i;
int x1 = 0;
int x2 = 0;
int x3 = 0;
int x4 = 0;
int x5 = 0;
int tempX = 0;
int tempY = 0;
int tempZ = 0;
int temp[3][ARRAY_LEN];
int time[ARRAY_LEN];

int median(int x1, int x2, int x3);
void readAccel1(int &x, int &y, int &z);
void readAccel2(int &x, int &y, int &z);
void checkFileLength(int &file_length, int &file_number);

task main() {
    int counter, counter_write, counter_file;
    FILENAME = "accel2-";

    string file = FILENAME;
    int startX = 0;
		readAccel1(startX, tempY, tempZ);

    strcat(file,"1.dat");
    i = 0;
    counter_file = 1;
		ClearTimer(T2);
    ClearTimer(T1);
    nxtDisplayCenteredTextLine(2, "%d", time1[T1]);
    while(time1[T1] < (COUNTDOWN * 1000)) {
    		if (time1[T2] >= 3000){
    			motor[driveRight] = 0;
    			motor[driveLeft] = 0;
    		}else if (time1[T2] >= 500){
    			motor[driveRight] = 100;
    			motor[driveLeft] = -100;
    		}
        x1 = x2;
        x2 = x3;
        x3 = x4;
        x4 = x5;
        readAccel1(x5, temp[1][i], temp[2][i]);
        tempX = median((tempX+x5)/2,median(x1,x2,x3),(x1+x2+x3+x4+x5)/5);
        temp[0][i] = tempX;
        time[i++] = time1[T1];
    }

    closeWriteTextFile();

    motor[driveRight] = 0;
    motor[driveLeft] = 0;

    counter = 0;
    FILENAME = "accel1-";
    counter = 0;
    counter_write = 0;
    counter_file = 1;

    file = FILENAME;

    strcat(file,"1.dat");

    bOpenWriteTextFile(file, kMaxFileSize);

    //for(i = 0; i < ARRAY_LEN; i++)
    i=0;
    while (time[i] > 0)
    	{
        writeIntegerNumber(counter++);
        writeIntegerNumber(time[i]);
        writeIntegerNumber(temp[0][i]);
        writeIntegerNumber(temp[1][i]);
        writeIntegerNumber(temp[2][i]);
        writeNewLine();
        counter_write++;
        checkFileLength(counter_write, counter_file);
        i++;
    }

    closeWriteTextFile();
    StopAllTasks();
}

void readAccel1(int &x, int &y, int &z) {
    HTACreadAllAxes(snsr_accel1, x, y, z);
    return;
}

void readAccel2(int &x, int &y, int &z) {
    HTACreadAllAxes(snsr_accel2, x, y, z);
    return;
}

void checkFileLength(int &file_length, int &file_number) {
    if(file_length > MAX_FILESIZE) {
        file_length = 0;
        closeWriteTextFile();
        file_number++;
        string str = "";
        string new_file;
        strcat(new_file,FILENAME);
        StringFormat(str,"%d",file_number);
        strcat(new_file,str);
        strcat(new_file,".dat");
        nxtDisplayCenteredTextLine(3, "%s", new_file);
        wait10Msec(100);
        bOpenWriteTextFile(new_file, kMaxFileSize);
    }
    return;
}

int median(int x1, int x2, int x3){
	if (x1<x2){
		if (x2<x3){
			return x2;
		}else{
			return x3;
		}
	}else{
		if (x1<x3){
			return x1;
		}else{
			return x3;
		}
	}
}
